### PR TITLE
Release `1.4.2`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `1.4.2` release.
Here you can find all related translations changes: [1.4.1...master](https://github.com/flarum-lang/german/compare/1.4.1...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## 1.4.2

**Allgemeine Änderungen**:

* Flarum-Core Übersetzungen aktualisiert.

**Übersetzungen für Erweiterungen aktualisiert**:

* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/subscriptions`](https://github.com/flarum/subscriptions)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`fof/spamblock`](https://github.com/FriendsOfFlarum/spamblock)

Alle Änderungen: [1.4.1...1.4.2](https://github.com/flarum-lang/german/compare/1.4.1...1.4.2).

</details>

### CODE REVIEW

**Comment by Kakifrucht** [comment]
@rob006 so far I have always matched the version number of Flarum with the language pack. Can I still bump this to 1.5.0 instead?

**Comment by rob006** [comment]
Versioning scheme follows semver, so bot will bump it to `1.5.0` when you add translations for new extension. But I think it is just a bad idea to sync language pack version with Flarum version - it creates unnecessary constraints and confusing conventions while does not bring any actual benefits.

**Comment by Kakifrucht** [comment]
Yes I'm not dead set on keeping it that way. The benefit would be that you could know from the version number if it fully supports your Flarum version, but since that is not a convention across language packs (and in general) it is probably not that useful, I agree. For example when updating you could immediately tell just from composer patching if your language pack is already fully ready aswell, I thought that was helpful especially during beta.

I'm just going to go with the bots defaults then.

**Review by Kakifrucht — APPROVED** [review]

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## Version [`1.4.2`](https://github.com/flarum-lang/german/releases/tag/1.4.2)

**Allgemeine Änderungen**:

* Flarum-Core Übersetzungen aktualisiert.


**Übersetzungen für Erweiterungen aktualisiert**:

* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/subscriptions`](https://github.com/flarum/subscriptions)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`fof/spamblock`](https://github.com/FriendsOfFlarum/spamblock)


Alle Änderungen: [1.4.1...1.4.2](https://github.com/flarum-lang/german/compare/1.4.1...1.4.2).

Führe folgende Befehle aus um zu aktualisieren:

```console
composer update flarum-lang/german
php flarum cache:clear
```

~~~

**Pull request merged**
