### PR TITLE
Release `1.4.1`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `1.4.1` release.
Here you can find all related translations changes: [1.4.0...master](https://github.com/flarum-lang/german/compare/1.4.0...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should [approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request) this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release.

<details>
<summary>Show release notes preview</summary>

## 1.4.1

**Updated translations for extensions**:

* [`clarkwinkelmann/flarum-ext-first-post-approval`](https://github.com/clarkwinkelmann/flarum-ext-first-post-approval)
* [`nearata/flarum-ext-minecraft-avatars`](https://github.com/Nearata/flarum-ext-minecraft-avatars)

All changes: [1.4.0...1.4.1](https://github.com/flarum-lang/german/compare/1.4.0...1.4.1).

</details>

### CODE REVIEW

**Comment by rob006** [comment]
@Kakifrucht Just as a note, this is an automated PR generated by bot. The idea is to simplify release process for language pack maintainers - all you need is to approve this pull request and bot will handle the rest. You can read more about the process at forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76 . If you don't want to use this feature, let me know.

**Comment by Kakifrucht** [comment]
Yes great feature, will approve once there are enough changes!

**Comment by rob006** [comment]
@Kakifrucht The main goal of this feature is to simplify release process, so maintainers could release more often. So don't hesitate to release more frequently, it is better to tag release with one change than waiting ~2 weeks for more updates.

**Comment by Kakifrucht** [comment]
I'll definitely tag more frequently with this, but I feel like there will still be some threshold that I feel should be met before I tag a new release. Gonna approve this to see how it goes.

**Review by Kakifrucht — APPROVED** [review]

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## Version [`1.4.1`](https://github.com/flarum-lang/german/releases/tag/1.4.1)

**Updated translations for extensions**:

* [`clarkwinkelmann/flarum-ext-first-post-approval`](https://github.com/clarkwinkelmann/flarum-ext-first-post-approval)
* [`nearata/flarum-ext-minecraft-avatars`](https://github.com/Nearata/flarum-ext-minecraft-avatars)


All changes: [1.4.0...1.4.1](https://github.com/flarum-lang/german/compare/1.4.0...1.4.1).

In order to update run these commands:

```console
composer update flarum-lang/german
php flarum cache:clear
```

~~~

**Comment by rob006** [comment]
Bot should react faster in the future - I forgot to setup webhook, but it is all configured now.

**Pull request merged**
