### PR TITLE
Forgot parameters: Users was not translated!

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@Kakifrucht 

Hello?

**Comment by Kakifrucht** [comment]
Sorry for late reply, I was busy during the weekend!

Thank you very much for noticing that this one slipped through. I was actually quite sure that I had added this and didn't yet investigate why it wasn't translated in the Admin CP. This also reminds me that this wouldn't have happened if we had Weblate integrated already, so I'll be sure to get that going asap, aswell as checking your other PR's.

**Comment by Kakifrucht** [comment]
This explains why I thought I took care of it: https://github.com/flarum-lang/german/commit/46cd4e751bda4e07fb0a965b32c129ccef731112

**Comment by Justman10000** [comment]
> 
> 
> This explains why I thought I took care of it: [46cd4e7](https://github.com/flarum-lang/german/commit/46cd4e751bda4e07fb0a965b32c129ccef731112)

Uff 😅

**Pull request merged**
