### PR TITLE
Übersetzung hinzugefügt

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Kakifrucht** [comment]
This has become quite difficult for me to manage. I would appreciate it if you could split all translations across PR's, so I can get to them one by one, and merge them one by one. In order for me to not get crazy it would also be nice if you could add the extension name as the pull/commit title.

The alternative is that I close these pulls, start the integration with Flarum Weblate and you resubmit the translations there? Let me know what you prefer.

**Comment by Justman10000** [comment]
Close these here... Then upload them individually...

**Comment by Kakifrucht** [comment]
I'll let you know when Weblate is ready!

**Comment by Justman10000** [comment]
> 
> 
> I'll let you know when Weblate is ready!

I would actually prefer it here

**Comment by Justman10000** [comment]
Sie könnten dies hier ja schon mal mergen, werde dann alles zukünftige in einzelne Pulls senden...

**Pull request closed without merging**
